### ISSUE TITLE
tvOS

### ISSUE THREAD

**Issue by iOlivier** [maximbilan/ios_swift_in_app_purchases_sample#1]
I tried to use this code in an app for the Apple TV (tvOS) but it doesn't work. I don't get any build errors either.
Can someone please make a small tvOS demo?

**Comment by iOlivier** [comment]
I found the solution.
Apparently in tvOS you have to set "productsRequest" as global variable in order to get it working.

**Comment by maximbilan** [comment]
I am glad that you found a solution.
